2025-08-17 16:57:26,651 - __main__ - INFO - ✅ Webhook установлен: https://634faef9ca12.ngrok-free.app/webhook
2025-08-17 16:57:31,418 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:57:31,418 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:57:31,901 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:57:31,901 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:57:32,942 - aiogram.event - INFO - Update id=618072167 is handled. Duration 2187 ms by bot id=7694884544
2025-08-17 16:57:32,943 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:57:30 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:14,767 - __main__ - INFO - ❌ Webhook удалён
2025-08-17 16:58:14,832 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000249229A6950>
2025-08-17 16:58:18,867 - __main__ - INFO - ✅ Webhook установлен: https://634faef9ca12.ngrok-free.app/webhook
2025-08-17 16:58:19,882 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:19,882 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:20,352 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:20,352 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:21,102 - aiogram.event - INFO - Update id=618072168 is handled. Duration 1889 ms by bot id=7694884544
2025-08-17 16:58:21,112 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:19 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:23,401 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:23,401 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:24,086 - aiogram.event - INFO - Update id=618072169 is handled. Duration 1141 ms by bot id=7694884544
2025-08-17 16:58:24,086 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:22 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:25,783 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:25,783 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:26,241 - aiogram.event - INFO - Update id=618072170 is handled. Duration 937 ms by bot id=7694884544
2025-08-17 16:58:26,241 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:25 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:29,052 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:29,052 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:29,701 - aiogram.event - INFO - Update id=618072171 is handled. Duration 1157 ms by bot id=7694884544
2025-08-17 16:58:29,705 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:28 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:31,725 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:31,725 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:32,214 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/by-role/1/ | Status: 200
2025-08-17 16:58:32,214 - databases.director.database - INFO - Response: [{'id': 4, 'telegram_id': 922337276000, 'first_name': 'Doston', 'phone_number': '+998908009090', 'language': 'st', 'photo': None, 'description': None, 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [1]}]
2025-08-17 16:58:32,506 - aiogram.event - INFO - Update id=618072172 is handled. Duration 1266 ms by bot id=7694884544
2025-08-17 16:58:32,507 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:31 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:33,783 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:33,783 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:34,255 - aiogram.event - INFO - Update id=618072173 is handled. Duration 937 ms by bot id=7694884544
2025-08-17 16:58:34,256 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:33 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:36,483 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:36,483 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:37,283 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/by-role/1/ | Status: 200
2025-08-17 16:58:37,283 - databases.director.database - INFO - Response: [{'id': 4, 'telegram_id': 922337276000, 'first_name': 'Doston', 'phone_number': '+998908009090', 'language': 'st', 'photo': None, 'description': None, 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [1]}]
2025-08-17 16:58:37,485 - aiogram.event - INFO - Update id=618072174 is handled. Duration 1483 ms by bot id=7694884544
2025-08-17 16:58:37,495 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:36 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:39,544 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:39,544 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:40,328 - aiogram.event - INFO - Update id=618072175 is handled. Duration 1266 ms by bot id=7694884544
2025-08-17 16:58:40,329 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:39 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:43,018 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:43,018 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:43,168 - aiogram.event - INFO - Update id=618072176 is handled. Duration 625 ms by bot id=7694884544
2025-08-17 16:58:43,180 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:42 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 16:58:46,349 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:46,349 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:46,350 - aiogram.event - INFO - Update id=618072177 is not handled. Duration 500 ms by bot id=7694884544
2025-08-17 16:58:46,350 - __main__ - ERROR - Ошибка обработки запроса: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D000>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D000>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D000>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D000>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
Traceback (most recent call last):
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\main.py", line 55, in handle
    await dp.feed_update(bot, update)
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\middlewares\ban.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\handlers\director\handler.py", line 496, in bookings
    await message.bot.send_message(
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\client\bot.py", line 2836, in send_message
    call = SendMessage(
           ^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D000>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D000>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D000>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D000>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
2025-08-17 16:58:46,365 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:45 +0500] "POST /webhook HTTP/1.1" 500 131 "-" "-"
2025-08-17 16:58:47,054 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:47,054 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:47,054 - aiogram.event - INFO - Update id=618072177 is not handled. Duration 467 ms by bot id=7694884544
2025-08-17 16:58:47,054 - __main__ - ERROR - Ошибка обработки запроса: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D480>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D480>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D480>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D480>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
Traceback (most recent call last):
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\main.py", line 55, in handle
    await dp.feed_update(bot, update)
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\middlewares\ban.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\handlers\director\handler.py", line 496, in bookings
    await message.bot.send_message(
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\client\bot.py", line 2836, in send_message
    call = SendMessage(
           ^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D480>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D480>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D480>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D480>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
2025-08-17 16:58:47,061 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:46 +0500] "POST /webhook HTTP/1.1" 500 131 "-" "-"
2025-08-17 16:58:49,751 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:49,751 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:49,751 - aiogram.event - INFO - Update id=618072177 is not handled. Duration 469 ms by bot id=7694884544
2025-08-17 16:58:49,751 - __main__ - ERROR - Ошибка обработки запроса: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D360>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D360>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D360>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D360>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
Traceback (most recent call last):
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\main.py", line 55, in handle
    await dp.feed_update(bot, update)
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\middlewares\ban.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\handlers\director\handler.py", line 496, in bookings
    await message.bot.send_message(
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\client\bot.py", line 2836, in send_message
    call = SendMessage(
           ^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D360>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D360>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D360>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D360>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
2025-08-17 16:58:49,751 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:49 +0500] "POST /webhook HTTP/1.1" 500 131 "-" "-"
2025-08-17 16:58:54,958 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 16:58:54,958 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 16:58:54,958 - aiogram.event - INFO - Update id=618072177 is not handled. Duration 703 ms by bot id=7694884544
2025-08-17 16:58:54,958 - __main__ - ERROR - Ошибка обработки запроса: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D5A0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D5A0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D5A0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D5A0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
Traceback (most recent call last):
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\main.py", line 55, in handle
    await dp.feed_update(bot, update)
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\middlewares\ban.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\barber_new\handlers\director\handler.py", line 496, in bookings
    await message.bot.send_message(
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\aiogram\client\bot.py", line 2836, in send_message
    call = SendMessage(
           ^^^^^^^^^^^^
  File "C:\Users\Uuser1\Desktop\barber_admin\.venv\Lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for SendMessage
reply_markup.InlineKeyboardMarkup
  Input should be a valid dictionary or instance of InlineKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D5A0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardMarkup
  Input should be a valid dictionary or instance of ReplyKeyboardMarkup [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D5A0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ReplyKeyboardRemove
  Input should be a valid dictionary or instance of ReplyKeyboardRemove [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D5A0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
reply_markup.ForceReply
  Input should be a valid dictionary or instance of ForceReply [type=model_type, input_value=<coroutine object today_b...s at 0x000002AE9366D5A0>, input_type=coroutine]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
2025-08-17 16:58:54,960 - aiohttp.access - INFO - ::1 [17/Aug/2025:16:58:54 +0500] "POST /webhook HTTP/1.1" 500 131 "-" "-"
2025-08-17 16:59:00,267 - __main__ - INFO - ❌ Webhook удалён
2025-08-17 16:59:00,308 - asyncio - ERROR - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002AE937403D0>
2025-08-17 16:59:00,324 - asyncio - ERROR - Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x000002AE93662F90>, 170179.453)])']
connector: <aiohttp.connector.TCPConnector object at 0x000002AE9372B490>
2025-08-17 17:42:15,101 - __main__ - INFO - ✅ Webhook установлен: https://634faef9ca12.ngrok-free.app/webhook
2025-08-17 17:42:15,867 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:15,867 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:16,335 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:16,335 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:17,076 - aiogram.event - INFO - Update id=618072177 is handled. Duration 1860 ms by bot id=7694884544
2025-08-17 17:42:17,076 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:42:15 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:42:17,672 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:17,672 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:17,835 - aiogram.event - INFO - Update id=618072178 is handled. Duration 625 ms by bot id=7694884544
2025-08-17 17:42:17,839 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:42:17 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:42:18,851 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:18,851 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:19,002 - aiogram.event - INFO - Update id=618072179 is handled. Duration 1046 ms by bot id=7694884544
2025-08-17 17:42:19,017 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:42:17 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:42:19,637 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:19,637 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:19,806 - aiogram.event - INFO - Update id=618072180 is handled. Duration 640 ms by bot id=7694884544
2025-08-17 17:42:19,807 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:42:19 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:42:22,999 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:22,999 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:23,184 - aiogram.event - INFO - Update id=618072181 is handled. Duration 640 ms by bot id=7694884544
2025-08-17 17:42:23,185 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:42:22 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:42:25,115 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:25,115 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:25,265 - aiogram.event - INFO - Update id=618072182 is handled. Duration 656 ms by bot id=7694884544
2025-08-17 17:42:25,266 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:42:24 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:42:28,167 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:28,167 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:28,321 - aiogram.event - INFO - Update id=618072183 is handled. Duration 594 ms by bot id=7694884544
2025-08-17 17:42:28,332 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:42:27 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:42:35,036 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:42:35,036 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:42:35,251 - aiogram.event - INFO - Update id=618072184 is handled. Duration 671 ms by bot id=7694884544
2025-08-17 17:42:35,256 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:42:34 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:43:01,885 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:43:01,885 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:43:02,366 - aiogram.event - INFO - Update id=618072185 is handled. Duration 1108 ms by bot id=7694884544
2025-08-17 17:43:02,367 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:43:01 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:43:26,614 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:43:26,614 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:43:27,058 - aiogram.event - INFO - Update id=618072186 is handled. Duration 1217 ms by bot id=7694884544
2025-08-17 17:43:27,073 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:43:25 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
2025-08-17 17:44:14,151 - databases.director.database - INFO - [API] GET http://20.124.93.156:8080/api/auth/users/if_exists/5012184829/ | Status: 200
2025-08-17 17:44:14,151 - databases.director.database - INFO - Response: {'id': 3, 'telegram_id': 5012184829, 'first_name': 'Shokha', 'phone_number': '+998900210160', 'language': 'uz', 'photo': None, 'description': '', 'rating': None, 'default_from_hour': '09:00:00', 'default_to_hour': '18:00:00', 'roles': [2, 3]}
2025-08-17 17:44:14,571 - aiogram.event - INFO - Update id=618072187 is handled. Duration 1125 ms by bot id=7694884544
2025-08-17 17:44:14,573 - aiohttp.access - INFO - ::1 [17/Aug/2025:17:44:13 +0500] "POST /webhook HTTP/1.1" 200 112 "-" "-"
